apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - image: django-backend:latest
          name: django-backend
          imagePullPolicy: Never
          command: ["python", "./manage.py", "migrate"]
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: localhost 127.0.0.1 0.0.0.0 172.17.0.4 192.168.64.2

            - name: SQL_HOST
              value: django-mysql

            - name: SQL_DATABASE
              value: mysql

            - name: SQL_USER
              value: root

            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-pass
                  key: password
              
      restartPolicy: Never
  backoffLimit: 5