apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: django-backend
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: django-backend
spec:
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - image: django-backend:latest
        name: django-backend
        imagePullPolicy: Never
        command: ["python", "./manage.py", "runserver", "0.0.0.0:8000"]
        env:
        - name: DJANGO_ALLOWED_HOSTS
          value: localhost 127.0.0.1 0.0.0.0 172.17.0.4 192.168.64.2

        - name: SQL_HOST
          value: django-mysql

        - name: SQL_DATABASE
          value: mysql

        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: user-pass
              key: user

        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-pass
              key: password

        # - name: SQL_USER
        #   value: root

        # - name: SQL_PASSWORD
        #   value: password

        ports:
        - containerPort: 8000
          name: django-backend