version: "3.7"
   
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django_code
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            # MYSQL_USER: 'user'
            # You can use whatever password you like
            # MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes: 
            - my-db:/var/lib/mysql 

volumes:
    my-db:
